### ISSUE TITLE
testing against oldest dependencies across federation

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1339]
Many of the federated packages are not testing against oldest versions of their dependencies. While this is not a critical need, we should keep track of which ones do/don't and attempt to close the gap as time & bandwidth permit.

* `...-oldest` -- pinned to oldest supported Python version & packages

------------------------

* [ ] `pysal/pysal` 
* [ ] `pysal/access`
* [x] `pysal/esda`
* [ ] `pysal/giddy`
* [x] `pysal/inequality` – but need to rename to [`-oldest`](https://github.com/pysal/pysal/issues/1338)
* [x] `pysal/libpysal`
* [x] `pysal/mapclassify` – but need to rename to [`-oldest`](https://github.com/pysal/pysal/issues/1338)
* [ ] `pysal/mgwr`
* [x] `pysal/momepy`
* [ ] `pysal/legendgram`
* [ ] `pysal/pointpats` – but need to rename to [`-oldest`](https://github.com/pysal/pysal/issues/1338)
* [ ] `pysal/segregation`
* [x] `pysal/spaghetti`
* [x] `pysal/spglm` – but need to rename to [`-oldest`](https://github.com/pysal/pysal/issues/1338)
* [ ] `pysal/spint`
* [x] `pysal/splot` – but need to rename to [`-oldest`](https://github.com/pysal/pysal/issues/1338)
* [x] `pysal/spopt`
* [ ] `pysal/spreg`
* [ ] ~~`pysal/spvcm`~~ ***archived***
* [ ] `pysal/tobler`

**Comment by jGaboardi** [comment]
#1375
